# 2022 알고리즘 캠프

* 문제 목록 : https://paullabworkspace.notion.site/2022-1a9af27342374d8b9cf5aafccf1dc849
* 모든 문제의 풀이가 있지는 않습니다. 풀이시간을 주신 문제에 한하여 풀이를 하였습니다.

# 가장 많이 사용된 알파벳

In [ ]:
# https://www.acmicpc.net/problem/1157
# 알파벳 대소문자로 된 단어가 주어지면, 이 단어에서 가장 많이 사용된 알파벳이 무엇인지 알아내는 프로그램을 작성하시오. 단, 대문자와 소문자를 구분하지 않는다. 출력은 대문자로 한다.

In [ ]:
txt = 'aaabbAABBCCC'.lower()
print(txt)
set(txt)
s = set(txt)

aaabbaabbccc


In [ ]:
l = []
for i in s:
    l.append([i, txt.count(i)])

l

[['c', 3], ['b', 4], ['a', 5]]

In [ ]:
l.sort(key=lambda x:x[1], reverse=True)
l[0][0].upper()

'A'

In [ ]:
from collections import Counter

sorted(Counter('aaabbAABBCCC'.lower()))

['a', 'b', 'c']

In [ ]:
sorted(Counter('aaabbAABBCCC'.lower()).items(), key=lambda x:x[1], reverse=True)

[('a', 5), ('b', 4), ('c', 3)]

In [ ]:
result = sorted(Counter('aaabbAABBCCC'.lower()).items(), key=lambda x:x[1], reverse=True)

if result[0][1] == result[1][1]:
    print('?')
else:
    print(result[0][0].upper())

A


# H-index

In [ ]:
# https://school.programmers.co.kr/learn/courses/30/lessons/42747
# [3, 0, 6, 1, 5]	3
# 이 과학자가 발표한 논문의 수는 5편이고, 그중 3편의 논문은 3회 이상 인용되었습니다. 그리고 나머지 2편의 논문은 3회 이하 인용되었기 때문에 이 과학자의 H-Index는 3입니다.

```
[3, 0, 6, 1, 5]
번 인용       편
1             4(>=1, true)
2             3(>=2, true)
3             3(>=3, true)
4             2(>=4, false)
5             1(>=5, false)
6             1(>=6, false)
```

In [ ]:
value = [3, 0, 6, 1, 5]
maxvalue = [3, 0, 6, 1, 5]

# [0, 1, 3, 5, 6] : 3
# [0, 1, 2, 5, 6] : 2
# [0, 5, 6, 8, 12] : 4

In [ ]:
# value = [0, 5, 6, 8, 12]
# value = [0, 1, 2, 5, 6]
value = [3, 0, 6, 1, 5]
l = []

def 카운팅(i, value):
    count = 0
    for j in value:
        print(j, i)
        if j >= i:
            count += 1
    return count

for 인용횟수 in range(1, max(value)):
    print(인용횟수)
    인용편 = 카운팅(인용횟수, value)
    l.append([인용횟수, 인용편, 인용편>=인용횟수])

l

1
3 1
0 1
6 1
1 1
5 1
2
3 2
0 2
6 2
1 2
5 2
3
3 3
0 3
6 3
1 3
5 3
4
3 4
0 4
6 4
1 4
5 4
5
3 5
0 5
6 5
1 5
5 5


[[1, 4, True], [2, 3, True], [3, 3, True], [4, 2, False], [5, 2, False]]

In [ ]:
value = [0, 5, 6, 8, 12]
# value = [0, 1, 2, 5, 6]
# value = [3, 0, 6, 1, 5]
l = []

def 카운팅(i, value):
    count = 0
    for j in value:
        # print(j, i)
        if j >= i:
            count += 1
    return count

for 인용횟수 in range(1, max(value)):
    # print(인용횟수)
    인용편 = 카운팅(인용횟수, value)
    l.append([인용횟수, 인용편, 인용편>=인용횟수])

list(filter(lambda x:x[2]==True, l))
list(filter(lambda x:x[2]==True, l))[-1][0]
l

[[1, 4, True],
 [2, 4, True],
 [3, 4, True],
 [4, 4, True],
 [5, 4, False],
 [6, 3, False],
 [7, 2, False],
 [8, 2, False],
 [9, 1, False],
 [10, 1, False],
 [11, 1, False]]

In [ ]:
def 카운팅(i, 논문):
    인용수 = 0
    for j in 논문:
        # print(j, i)
        if j >= i:
            인용수 += 1
    return 인용수

def solution(논문):
    ㅣ = []
    for 인용횟수 in range(1, max(논문)):
    # print(인용횟수)
        인용편 = 카운팅(인용횟수, 논문)
        l.append([인용횟수, 인용편, 인용편>=인용횟수])

    return list(filter(lambda x:x[2]==True, l))[-1][0]

# solution([3, 0, 6, 1, 5])
solution([0, 1, 2, 5, 6])

2

In [ ]:
# 런타임애러
def 카운팅(i, 논문):
    인용수 = 0
    for j in 논문:
        # print(j, i)
        if j >= i:
            인용수 += 1
    return 인용수

def solution(논문):
    l = []
    for 인용횟수 in range(1, max(논문)):
    # print(인용횟수)
        인용편 = 카운팅(인용횟수, 논문)
        l.append([인용횟수, 인용편, 인용편>=인용횟수])

    return list(filter(lambda x:x[2]==True, l))[-1][0]

# solution([3, 0, 6, 1, 5])
solution([0, 1, 2, 5, 6])

In [ ]:
# 런타임애러 해결
def 카운팅(i, 논문):
    인용수 = 0
    for j in 논문:
        if j >= i:
            인용수 += 1
    return 인용수

def solution(논문):
    h_index = 0
    for 인용횟수 in range(1, max(논문)):
        인용편 = 카운팅(인용횟수, 논문)
        if 인용편 >= 인용횟수:
            h_index = 인용횟수
        else:
            break
    return h_index

# solution([3, 0, 6, 1, 5])
solution([0, 1, 2, 5, 6])

3

# 가장 큰 직사각형

In [ ]:
# 가장 큰 직사각형
# https://leetcode.com/problems/largest-rectangle-in-histogram/

In [ ]:
import numpy as np

heights = [2,1,5,6,2,3]
rect = np.zeros((len(heights), max(heights))) # 옆으로 채워간다
rect

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((1, 5)) + np.ones((1, 5))
np.append(np.ones((1, 5)), np.ones((1, 5)))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
for i in range(len(rect)):
    rect[i] = np.append(np.ones((1, heights[i])), np.zeros((1, len(heights) - heights[i])))
rect

array([[1., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [ ]:
# set(heights)를 순회하며 최댓값을 구하여 해당 직사각형을 sum으로 연산
# shape 비교도 가능함

In [ ]:
rect.T

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 0., 1.],
       [0., 0., 1., 1., 0., 0.],
       [0., 0., 1., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [ ]:
합 = []
for i in range(len(rect.T)):
    부분합 = 0
    for j in range(len(rect.T[i])):
        # print(i, j)
        if rect.T[i][j] == 0:
            합.append([i, 부분합])
            부분합 = 0
        else:
            부분합 += 1
        if j == len(rect.T[i]) - 1:
            합.append([i, 부분합])
        # print(부분합)

합

[[0, 6],
 [1, 1],
 [1, 4],
 [2, 0],
 [2, 0],
 [2, 2],
 [2, 1],
 [3, 0],
 [3, 0],
 [3, 2],
 [3, 0],
 [3, 0],
 [4, 0],
 [4, 0],
 [4, 2],
 [4, 0],
 [4, 0],
 [5, 0],
 [5, 0],
 [5, 0],
 [5, 1],
 [5, 0],
 [5, 0]]

In [ ]:
합 = []
for i in range(len(rect.T)):
    부분합 = 0
    for j in range(len(rect.T[i])):
        # print(i, j)
        if rect.T[i][j] == 0:
            합.append([i, 부분합 * (i+1)])
            부분합 = 0
        else:
            부분합 += 1
        if j == len(rect.T[i]) - 1:
            합.append([i, 부분합 * (i+1)])
        # print(부분합)

합

[[0, 6],
 [1, 2],
 [1, 8],
 [2, 0],
 [2, 0],
 [2, 6],
 [2, 3],
 [3, 0],
 [3, 0],
 [3, 8],
 [3, 0],
 [3, 0],
 [4, 0],
 [4, 0],
 [4, 10],
 [4, 0],
 [4, 0],
 [5, 0],
 [5, 0],
 [5, 0],
 [5, 6],
 [5, 0],
 [5, 0]]

In [ ]:
sorted(합, key=lambda x:x[1], reverse=True)

[[4, 10],
 [1, 8],
 [3, 8],
 [0, 6],
 [2, 6],
 [5, 6],
 [2, 3],
 [1, 2],
 [2, 0],
 [2, 0],
 [3, 0],
 [3, 0],
 [3, 0],
 [3, 0],
 [4, 0],
 [4, 0],
 [4, 0],
 [4, 0],
 [5, 0],
 [5, 0],
 [5, 0],
 [5, 0],
 [5, 0]]

In [ ]:
sorted(합, key=lambda x:x[1], reverse=True)[0][1]

10

# 스킬트리

In [ ]:
# 스킬트리
# https://school.programmers.co.kr/learn/courses/30/lessons/49993
# "CBD" ["BACDE", "CBADF", "AECB", "BDA"] 2

In [ ]:
# 일반적인 문자열 찾는 알고리즘으로 해당 패턴이 있는지만 확인(정답 X)
import re

p = re.compile("CBD")
p

re.compile(r'CBD', re.UNICODE)

In [ ]:
p.findall("BACDE")
p.findall("CDBDACDE")

[]

In [ ]:
import re

p = re.compile("[a-zA-Z]*[C][a-zA-Z]*[B][a-zA-Z]*[D][a-zA-Z]*")
p

re.compile(r'[a-zA-Z]*[C][a-zA-Z]*[B][a-zA-Z]*[D][a-zA-Z]*', re.UNICODE)

In [ ]:
p.findall("AAABBDACDE")

[]

In [ ]:
list("CBD")

['C', 'B', 'D']

In [ ]:
import re

def solution(스킬, 스킬트리):
    갯수  = 0
    패턴 = ''
    패턴조각 = list(스킬)
    정답 = 0
    print(패턴조각)
    if len(패턴조각) == 1:
        패턴 = '[a-zA-Z]*[' + 패턴조각[0] + '][a-zA-Z]*'
    else:
        for i in 패턴조각:
            print(i)
            패턴 = 패턴 + '][a-zA-Z]*[' + i
        패턴 = 패턴[1:] + '][a-zA-Z]*'

    패턴 = re.compile(패턴)
    for i in 스킬트리:
        if(패턴.findall(i)): 정답 += 1

    return 정답

print(solution("CBD", ["BACDE", "CBADF", "AECB", "BDA"]))

['C', 'B', 'D']
C
B
D
1


In [ ]:
# 정답코드

import re

def solution(스킬, 스킬트리):
    정답 = 0
    임시스킬 = f'[{스킬}]'
    트리길이 = len(스킬트리)
    패턴 = re.compile(f'{임시스킬}')
    for i in range(트리길이):
        스킬문자열들 = ''.join(패턴.findall(스킬트리[i])) 
        # print(스킬문자열들)
        for 하나, 둘 in zip(스킬, 스킬문자열들):
            if 하나 != 둘: break
        else: 정답 += 1
    return 정답

print(solution("CBD", ["BACDE", "CBADF", "AECB", "BDA"]))

2


In [ ]:
# 프로그래머스의 풀이
def solution(skill, skill_trees):
    def check(skill,branch):
        branch=list(filter(lambda x:x in skill,branch))
        checked=0
        for b in branch:
            if skill[checked]==b:
                checked=checked+1
            else:
                return 0
        return 1
    return sum(list(map(lambda x:check(skill,x),skill_trees)))